#!/usr/bin/env bash
#===================================================================================
#
#         FILE: test
#
#  DESCRIPTION: Analyzes and tests the code base.
#
#      OPTIONS: ---
# REQUIREMENTS: BITBUCKET_USERNAME, BITBUCKET_PASSWORD
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Gota Media
#      COMPANY: Gota Media AB
#      VERSION: 0.1.0
#      CREATED: 2019-02-14
#===================================================================================

set -e

source ci/functions.sh

assert-variables BITBUCKET_USERNAME \
                 BITBUCKET_PASSWORD

apk add --update libxml2-dev
docker-php-ext-install pdo pdo_mysql soap

composer config http-basic.bitbucket.org ${BITBUCKET_USERNAME} ${BITBUCKET_PASSWORD}
composer install --no-interaction --no-progress --prefer-dist --no-suggest

composer run lint
composer run analyze
composer run test
